In [1]:
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv("forestfires.csv")
data.head()

month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  ...  monthfeb  \
0   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0  ...         0   
1   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0  ...         0   
2   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0  ...         0   
3   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2  ...         0   
4   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   

   monthsep  size_category  
0         0          small  
1         0          small  
2         0          small  
3         0          small  
4         0          small  

[5 rows x 31 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   month          517 non-null    object 
 1   day            517 non-null    object 
 2   FFMC           517 non-null    float64
 3   DMC            517 non-null    float64
 4   DC             517 non-null    float64
 5   ISI            517 non-null    float64
 6   temp           517 non-null    float64
 7   RH             517 non-null    int64  
 8   wind           517 non-null    float64
 9   rain           517 non-null    float64
 10  area           517 non-null    float64
 11  dayfri         517 non-null    int64  
 12  daymon         517 non-null    int64  
 13  daysat         517 non-null    int64  
 14  daysun         517 non-null    int64  
 15  daythu         517 non-null    int64  
 16  daytue         517 non-null    int64  
 17  daywed         517 non-null    int64  
 18  monthapr  

In [4]:
data.isnull().sum()

month            0
day              0
FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

In [5]:
scale= StandardScaler()

In [6]:
D = pd.get_dummies(data['size_category'],drop_first=True)
D.tail()

small
512      0
513      0
514      0
515      1
516      1

In [7]:
DATA = pd.concat([data, D], axis = 1)
DATA

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthjan  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...       ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...         0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...         0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...         0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...         0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...         0   

     monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  monthsep  \
0           0         0         1         0         0         0         0   
1           0         0         0         0         0         1         0   
2           0         0         0         0         0         1         0   
3           0         0         1         0         0         0         0   
4           0         0         1         0         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         1         0         0   

     size_category  small  
0            small      1  
1            small      1  
2            small      1  
3            small      1  
4            small      1  
..             ...    ...  
512          large      0  
513          large      0  
514          large      0  
515          small      1  
516          small      1  

[517 rows x 32 columns]

In [8]:
X = data.iloc[:, 18:-1]
y = DATA['small']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 15, test_size = 0.25)
X_test

monthapr  monthaug  monthdec  monthfeb  monthjan  monthjul  monthjun  \
254         0         1         0         0         0         0         0   
408         0         0         0         0         0         0         0   
235         0         1         0         0         0         0         0   
128         0         0         0         0         0         0         0   
435         0         0         0         0         0         1         0   
..        ...       ...       ...       ...       ...       ...       ...   
477         0         0         0         0         0         1         0   
496         0         1         0         0         0         0         0   
314         0         0         0         0         0         0         0   
158         0         1         0         0         0         0         0   
349         0         0         0         0         0         0         0   

     monthmar  monthmay  monthnov  monthoct  monthsep  
254         0         0         0         0         0  
408         0         0         0         0         1  
235         0         0         0         0         0  
128         0         0         0         1         0  
435         0         0         0         0         0  
..        ...       ...       ...       ...       ...  
477         0         0         0         0         0  
496         0         0         0         0         0  
314         0         0         0         0         1  
158         0         0         0         0         0  
349         0         0         0         0         1  

[130 rows x 12 columns]

In [10]:
scale.fit(X_train)

StandardScaler()

In [11]:
X_train_std = scale.transform(X_train)
X_test_std = scale.transform(X_test)

In [12]:
X_train_df = pd.DataFrame(X_train_std, columns = X_train.columns)
X_test_df = pd.DataFrame(X_test_std, columns = X_test.columns)

In [13]:
X_train_df.head()

monthapr  monthaug  monthdec  monthfeb  monthjan  monthjul  monthjun  \
0 -0.145287  1.328264 -0.145287 -0.220863 -0.072075 -0.273861 -0.178885   
1 -0.145287 -0.752862 -0.145287 -0.220863 -0.072075 -0.273861 -0.178885   
2 -0.145287 -0.752862 -0.145287 -0.220863 -0.072075 -0.273861 -0.178885   
3 -0.145287  1.328264 -0.145287 -0.220863 -0.072075 -0.273861 -0.178885   
4 -0.145287  1.328264 -0.145287 -0.220863 -0.072075 -0.273861 -0.178885   

   monthmar  monthmay  monthnov  monthoct  monthsep  
0 -0.325137 -0.050899       0.0 -0.171042 -0.682575  
1 -0.325137 -0.050899       0.0 -0.171042  1.465040  
2 -0.325137 -0.050899       0.0 -0.171042  1.465040  
3 -0.325137 -0.050899       0.0 -0.171042 -0.682575  
4 -0.325137 -0.050899       0.0 -0.171042 -0.682575

In [14]:
X_test_df.head()

monthapr  monthaug  monthdec  monthfeb  monthjan  monthjul  monthjun  \
0 -0.145287  1.328264 -0.145287 -0.220863 -0.072075 -0.273861 -0.178885   
1 -0.145287 -0.752862 -0.145287 -0.220863 -0.072075 -0.273861 -0.178885   
2 -0.145287  1.328264 -0.145287 -0.220863 -0.072075 -0.273861 -0.178885   
3 -0.145287 -0.752862 -0.145287 -0.220863 -0.072075 -0.273861 -0.178885   
4 -0.145287 -0.752862 -0.145287 -0.220863 -0.072075  3.651484 -0.178885   

   monthmar  monthmay  monthnov  monthoct  monthsep  
0 -0.325137 -0.050899       0.0 -0.171042 -0.682575  
1 -0.325137 -0.050899       0.0 -0.171042  1.465040  
2 -0.325137 -0.050899       0.0 -0.171042 -0.682575  
3 -0.325137 -0.050899       0.0  5.846522 -0.682575  
4 -0.325137 -0.050899       0.0 -0.171042 -0.682575

In [15]:
svm = SVC(C = 1.0, kernel = 'rbf', gamma = 0.50)

In [16]:
svm

SVC(gamma=0.5)

In [17]:
svm.fit(X_train_df, y_train)

SVC(gamma=0.5)

In [18]:
print("Acuracy of ##TRAINING DATA ## is: {:.2f} out of 100".format(svm.score(X_train_df, y_train)*100))

Acuracy of ##TRAINING DATA ## is: 75.19 out of 100


In [19]:
print("Accuracy of ## TESTING DATA ## is: {:.2f} out of 100".format(svm.score(X_test_df, y_test)*100))

Accuracy of ## TESTING DATA ## is: 72.31 out of 100


In [20]:
svm_indice = svm.support_

In [21]:
svm_indice

array([  0,   3,   5,   6,   7,  10,  13,  21,  26,  31,  34,  41,  42,
        43,  52,  63,  73,  79,  81,  83, 101, 103, 108, 109, 111, 115,
       119, 124, 125, 131, 133, 140, 148, 151, 152, 153, 165, 167, 168,
       176, 182, 184, 188, 190, 191, 194, 195, 202, 203, 207, 221, 228,
       234, 239, 243, 245, 249, 250, 254, 255, 260, 274, 277, 280, 283,
       288, 291, 295, 299, 300, 302, 308, 309, 316, 319, 322, 325, 326,
       328, 329, 333, 334, 336, 346, 349, 352, 357, 363, 364, 367, 370,
       374, 376, 377, 379, 380, 383, 385, 147, 150, 157, 205, 210, 220,
       225, 235, 237, 244, 247, 251, 252, 256, 257, 258, 259, 261, 262,
       263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 275, 276,
       278, 279, 281, 282, 284, 285, 286, 287, 289, 290, 292, 293, 294,
       296, 297, 298, 301, 303, 304, 305, 306, 307, 310, 311, 312, 313,
       314, 315, 317, 318, 320, 321, 323, 324, 327, 330, 331, 332, 335,
       337, 338, 339, 340, 341, 342, 343, 344, 345, 347, 348, 35

In [22]:
support_vectors = svm.support_vectors_

In [23]:
svm_class = svm.n_support_
svm_class

array([ 98, 106])

In [24]:
X_train

monthapr  monthaug  monthdec  monthfeb  monthjan  monthjul  monthjun  \
385         0         1         0         0         0         0         0   
462         0         0         0         0         0         0         0   
345         0         0         0         0         0         0         0   
438         0         1         0         0         0         0         0   
84          0         1         0         0         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
85          0         0         0         0         0         0         0   
199         0         0         0         0         0         0         0   
156         0         0         0         0         0         0         0   
384         0         1         0         0         0         0         0   
456         0         1         0         0         0         0         0   

     monthmar  monthmay  monthnov  monthoct  monthsep  
385         0         0         0         0         0  
462         0         0         0         0         1  
345         0         0         0         0         1  
438         0         0         0         0         0  
84          0         0         0         0         0  
..        ...       ...       ...       ...       ...  
85          0         0         0         0         1  
199         0         0         0         0         1  
156         0         0         0         0         1  
384         0         0         0         0         0  
456         0         0         0         0         0  

[387 rows x 12 columns]

In [25]:
X_train_arr = np.array(X_train)
X_train_arr

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
y_pred = svm.predict(X_test_df)

In [27]:
confusion_matrix(y_test, y_pred)

array([[ 0, 35],
       [ 1, 94]], dtype=int64)

In [28]:
accuracy_score(y_test, y_pred) * 100

72.3076923076923

In [29]:
svm = SVC(C = 13, kernel = 'linear', gamma = 45, random_state = 5)
svm

SVC(C=13, gamma=45, kernel='linear', random_state=5)

In [30]:
svm.fit(X_train_df, y_train)

SVC(C=13, gamma=45, kernel='linear', random_state=5)

In [31]:
y_pred1 = svm.predict(X_test_df)
y_pred1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=uint8)

In [32]:
print("Acuracy of ##TRAINING DATA ## is: {:.2f} out of 100".format(svm.score(X_train_df, y_train)*100))

Acuracy of ##TRAINING DATA ## is: 75.19 out of 100


In [33]:
print("Accuracy of ## TESTING DATA ## is: {:.2f} out of 100".format(svm.score(X_test_df, y_test)*100))

Accuracy of ## TESTING DATA ## is: 72.31 out of 100


In [34]:
confusion_matrix(y_test, y_pred1)

array([[ 0, 35],
       [ 1, 94]], dtype=int64)

In [35]:
y_test

254    0
408    0
235    0
128    1
435    1
      ..
477    0
496    1
314    1
158    1
349    1
Name: small, Length: 130, dtype: uint8

In [36]:
accuracy_score(y_pred1, y_test) * 100

72.3076923076923